const ACTION_TYPE = {
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SEND_LINK: 'SEND_LINK',
};
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';

export default ACTION_TYPE;
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const DO_NOTHING = 'DO_NOTHING';
export const Rate_Article = 'RATE_ARTICLE';
export const SHARE_ARTICLE = 'SHARE_ARTICLE';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const COMMENTS = {
  GET_COMMENTS: 'GET_COMMENTS',
  POST_COMMENT: 'POST_COMMENT',
};
export const BOOKMARK_ARTICLE = 'BOOKMARK_ARTICLE';
