export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const DO_NOTHING = 'DO_NOTHING';

const ACTION_TYPE = {
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SEND_LINK: 'SEND_LINK',
};
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';

export const COMMENTS = {
  GET_COMMENTS: 'GET_COMMENTS',
  POST_COMMENT: 'POST_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  CREATE_THREAD: 'CREATE_THREAD',
};

export default ACTION_TYPE;
