const mockArticles = [
  {
    slug: 'how-to-kill',
    title: 'How to kill',
    description: 'Ever wonder how?',
    body: 'Well there is no way to say this. its not easy so am not going to get into that right now. But yeah.Well i want to tell a story about this girl called jane, eh eh my brother fire pon the mountain cause stuff as lit man. No man shall curse. Jah bless. ',
    image_url: 'https://images.unsplash.com/photo-1524260855046-f743b3cdad07?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2001&q=80',
    tagList: ['dragons', 'training'],
    createdAt: '2016-02-18T03:22:56.637Z',
    updatedAt: '2016-02-18T03:48:35.824Z',
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'jake',
      bio: 'I work at statefarm',
      image: 'https://i.stack.imgur.com/xHWG8.jpg',
      following: false,
    },
    id: 1,
  },
  {
    slug: 'how-to-train-your-dragon',
    title: 'How to train your dragon',
    description: 'Ever wonder how?',
    body: 'It takes a Jacobian forever to go and eat a chicken without steaming it. Well there is no way to say this. its not easy so am not going to get into that right now. Sister fried rice and it was very hot. Hot and cold for this is how the world is. Nothing is easy.',
    image_url: ' https://images.unsplash.com/photo-1516692935701-4f35bff8b9f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
    tagList: ['dragons', 'training'],
    createdAt: '2016-02-18T03:22:56.637Z',
    updatedAt: '2016-02-18T03:48:35.824Z',
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'jake',
      bio: 'I work at statefarm',
      image: 'https://i.stack.imgur.com/xHWG8.jpg',
      following: false,
    },
    id: 2,
  },
  {
    slug: 'how-to-code',
    title: 'How to train your dragon',
    description: 'Ever wonder how?',
    body: 'For me life is simple, get to work and get my code done. just like that. Because you are hot and you cold, you are yes and you and you are no. You are in when you are out. We fight we breakup, we kiss we make up. I dont reaclly want to be with you.',
    image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
    tagList: ['code', 'bootcamp'],
    createdAt: '2019-01-15T03:22:56.637Z',
    updatedAt: '2019-01-15T03:48:35.824Z',
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'jake',
      bio: 'I work at statefarm',
      image: 'https://i.stack.imgur.com/xHWG8.jpg',
      following: false,
    },
    id: 3,
  },
  {
    slug: 'how-to-eat',
    title: 'How to train your dragon',
    description: 'Ever wonder how?',
    body: 'It takes a Jacobian, becasue the guy is a legit goat. Like what to do with it. ',
    image_url: 'https://images.unsplash.com/uploads/1411400493228e06a6315/ad711a20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
    tagList: ['dragons', 'training'],
    createdAt: '2019-01-10T03:22:56.637Z',
    updatedAt: '2019-01-14T03:48:35.824Z',
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'jake',
      bio: 'I work at statefarm',
      image: 'https://i.stack.imgur.com/xHWG8.jpg',
      following: false,
    },
    id: 4,
  },
  {
    slug: 'how-to-eat',
    title: 'How to train your dragon',
    description: 'Ever wonder how?',
    body: 'It takes a Jacobian, because this is the kind of life that is moving out of life and going to live in your own place for that is just how things go. you can be your own, you have to grow and live your own life. This is just hopeless.That is it.',
    image_url: 'https://images.unsplash.com/photo-1419332552192-47d29e59b1e0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1953&q=80',
    tagList: ['dragons', 'training'],
    createdAt: '2019-01-10T03:22:56.637Z',
    updatedAt: '2019-01-14T03:48:35.824Z',
    favorited: false,
    favoritesCount: 0,
    author: {
      username: 'jake',
      bio: 'I work at statefarm',
      image: 'https://i.stack.imgur.com/xHWG8.jpg',
      following: false,
    },
    id: 5,
  },
];

export default mockArticles;
